version: "3.9"
services:
  
  db:
    build: db
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: OpenCuisine
      MYSQL_ROOT_PASSWORD: root
    #volumes:
      #- ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: app
    links:
      - db
    ports:
      - 8000