version: "3.0"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - 5000
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./dbs/init.sql:/docker-entrypoint-initdb.d/init.sql:ro