version: "3.8"
services:
  app:
    build: ./app
    links:
      - db:db
    ports:
      - "5000:5000"
    networks:
      - app-tier
      
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge